[2023/12/19 PM 04:57:09] Run() Error!!! 引動過程的目標傳回例外狀況。
